version: 2
jobs:
  dependencies:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: dependencies-v1-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn cy:cache
      - run: yarn cy:ci
      - run: yarn report:coverage
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn build TINIFY_API_KEY_CI=$TINIFY_API_KEY
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
            - .cache
          key: dependencies-v1-{{ checksum "yarn.lock" }}
      - store_artifacts:
          path: build
          destination: build
workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test:
          requires:
          - dependencies
      - build:
          requires:
            - test
