version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: v2-dependencies-{{ checksum "package.json" }}
  test:
    requires:
      - dependencies
    docker:
      - image: cypress/base:10
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn cy:cache
      - run: yarn cy:ci
      - run: yarn report:coverage
      - save_cache:
            paths:
              - node_modules
              - /root/.cache/Cypress
            key: v2-dependencies-{{ checksum "package.json" }}
